# This is a basic workflow to help you get started with Actions

name: Check README.md (student answers)

# Controls when the workflow will run
on:
  # Triggers the workflow on push only for the "main" branch
  push:
    branches: 
      - 'main'
    paths:
      - 'README.md'
      - '**.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run check script script
        run: |
          chmod +x check_questions.sh
          ./check_questions.sh
